### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vbanait** [kshramt/company-ngram#3]
Windows 10
Python 3.8 properly in path 

Issue 
[issue](https://emacs.stackexchange.com/questions/61089/kindly-help-with-emacs-company-ngram-error)

**Comment by FelipeLema** [comment]
It would help the dev if you could provide more info.
- Does ngram_test.py run ok?
- Do you get any error?
- Can you run ngram.py on terminal?

**Comment by vbanait** [comment]
When running ngram_test.py from console, 
SyntaxError: unexpected character after line continuation character 
File"<stdin>" line 1

**Comment by FelipeLema** [comment]
I just ran `ngram_test.py` with python 3.7 on windows and got another error:

```
Traceback (most recent call last):
  File "ngram_test.py", line 7, in <module>
    import ngram as ng
  File "C:\Users\felipel\Downloads\company-ngram-master\ngram.py", line 17, in <module>
    cache_dir = os.path.join(os.environ['HOME'], '.cache', 'company-ngram')
  File "C:\Users\felipel\AppData\Local\Continuum\anaconda3\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

It seems that the code is incompatible with Windows and it's not a config error on user side. I don't know if @kshramt is currently maintaining this, so best shot right now is to fork and maintain a windows-compatible branch oneself
